background {
    path = /tmp/hyprlock.png
}

label {
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(ECEFF4ff)

    font_size = 90
    font_family = JetBrains Mono Nerd Font

    position = 0, 180
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] date +"%A %d %B"
    color = rgba(D8DEE9ff)

    font_size = 22
    font_family = JetBrains Mono Nerd Font

    position = 0, 110
    halign = center
    valign = center
}

input-field {
    size = 320, 60

    position = 0, -60
    halign = center
    valign = center

    outer_color = rgba(88C0D0ff)
    inner_color = rgba(2E3440cc)
    font_color = rgba(ECEFF4ff)

    check_color = rgba(8FBCBBff)
    fail_color = rgba(BF616Aff)

    rounding = 14
    outline_thickness = 2

    fade_on_empty = false
    dots_center = true

    placeholder_text = Password
}
