name: dotfiles-lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install shellcheck
        run: sudo apt-get install shellcheck -y

      - name: lint shell scripts
        run: find . -type f -name "*.sh" -exec shellcheck {} +
